### ISSUE TITLE
Please add screenshot to repository!

### ISSUE THREAD

**Issue by whyboris** [SuzannaWentzel/Moire#1]
The visual patterns that this project generates are beautiful! It would be easier to appreciate (and more-alluring to clone) the repository if a screenshot was added to the `README` 👍 

An easy way to add a screenshot is to paste a screenshot as a response to this _Issue_, copy the generated code, and paste it into the `README` 👌 

Cheers 🎉

**Comment by SuzannaWentzel** [comment]
Will do, great idea! Thanks for the hint!
